<?php
// Do not edit this file if you do not know what you do
// LEVELS = 0 - BANNED
// LEVELS = 1 - GUEST
// LEVELS = 2 - Tester
// LEVELS = 3 - GM ( EGM )
// LEVELS = 4 - GM ( HGM )
// LEVELS = 5 - GOD ( ADMIN )
// coded by ULTRA

$GLOBALS['CONFIG_ACCESS_LEVELS_0'] = '-100';
$GLOBALS['CONFIG_ACCESS_LEVELS_1'] = '0';
$GLOBALS['CONFIG_ACCESS_LEVELS_2'] = '20';
$GLOBALS['CONFIG_ACCESS_LEVELS_3'] = '50';
$GLOBALS['CONFIG_ACCESS_LEVELS_4'] = '80';
$GLOBALS['CONFIG_ACCESS_LEVELS_5'] = '8';
