<?php
// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel
$GLOBALS['DBQUERY_CHECK_ACCOUNT'] = 'SELECT * FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_CHAR'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_CLAN'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s in (SELECT %s FROM %s WHERE %s = \'%s\')';
$GLOBALS['DBQUERY_CHECK_EMAIL'] = 'SELECT * FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHECK_LOGIN'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s = %s';
$GLOBALS['DBQUERY_CHECK_STATS_ACCESS'] = 'SELECT * FROM %s WHERE %s = \'%s\' and %s in (\'%s\', \'%s\', \'%s\', \'7\')';
$GLOBALS['DBQUERY_ACCOUNT_DATA'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_SIGNATURE_ACC'] = 'SELECT SUM(%s), SUM(%s), SUM(%s) FROM %s WHERE %s = \'%s\'';

$GLOBALS['DBQUERY_CHAR_DATA'] = 'SELECT %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, (SELECT %s FROM %s WHERE %s=%s) FROM %s WHERE %s = \'%s\'';

$GLOBALS['DBQUERY_CLAN_DATA'] = 'SELECT %s, %s, %s, %s, (SELECT %s FROM %s WHERE %s = %s), (SELECT COUNT(*) FROM %s WHERE %s = %s) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_MEMBERS_DATA'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CREATE_ACCOUNT_L2J'] = 'INSERT INTO %s (%s, %s, %s, %s, %s) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';
$GLOBALS['DBQUERY_MCHECK_CREATE'] = 'INSERT INTO mail_check (username, email, password, ip, check_id, time, refer) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';
$GLOBALS['DBQUERY_MCHECK_CHECK'] = 'SELECT * FROM mail_check WHERE username = \'%s\' and check_id = \'%s\' and ip = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_DATA'] = 'SELECT username, email, password, refer FROM mail_check WHERE username = \'%s\' and check_id = \'%s\' and ip = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_DELETE'] = 'DELETE FROM mail_check WHERE username = \'%s\'';
$GLOBALS['DBQUERY_MCHECK_CHECK_EXPIRED'] = 'SELECT * FROM mail_check WHERE username = \'%s\' and time <= \'%s\'';
$GLOBALS['DBQUERY_1_1'] = 'SELECT %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_1_1N'] = 'SELECT %s FROM %s WHERE %s = %s';
$GLOBALS['DBQUERY_2_1'] = 'SELECT %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_3_1'] = 'SELECT %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_LAST_LOGGED'] = 'SELECT %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CHANGE_PASSWORD'] = 'UPDATE %s SET %s=%s WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_CHANGE_VIEWSET'] = 'UPDATE %s SET %s=\'%s\' WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_CHANGE_SIGNATURE'] = 'UPDATE %s SET %s=\'%s\' WHERE %s=\'%s\'';
$GLOBALS['DBQUERY_PLAYERS_ONLINE'] = 'SELECT COUNT(*) FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_CASTLES'] = 'SELECT %s, %s, (SELECT %s FROM %s WHERE %s = %s), (SELECT %s FROM %s WHERE %s = (SELECT %s FROM %s WHERE %s = %s)) FROM %s';
$GLOBALS['DBQUERY_RAIDS'] = 'SELECT %s, %s, %s FROM %s JOIN %s ON %s = %s and %s >= \'%s\' and %s <= \'%s\'';
$GLOBALS['DBQUERY_TOP_PVP'] = 'SELECT %s, %s, %s FROM %s WHERE %s >= \'%s\'';
$GLOBALS['DBQUERY_TOP_PK'] = 'SELECT %s, %s, %s FROM %s WHERE %s >= \'%s\'';
$GLOBALS['DBQUERY_ADD_POINTS'] = 'UPDATE %s SET %s = %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_ADD_REFER_POINTS'] = 'UPDATE %s SET %s = %s + 1 WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_REMOVE_POINTS'] = 'UPDATE %s SET %s = %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_SKILLS_DATA'] = 'SELECT %s, %s FROM %s WHERE %s = \'%s\' and %s = \'%s\'';
$GLOBALS['DBQUERY_INVENTORY_DATA'] = 'SELECT %s, %s, %s, %s, %s FROM %s WHERE %s = \'%s\'';
$GLOBALS['DBQUERY_STAT_SUM'] = 'SELECT SUM(%s) FROM %s';

$GLOBALS['DBQUERY_OBJECT_ITEM'] = 'SELECT MAX(object_id) FROM items';
$GLOBALS['DBQUERY_GIVE_ITEM'] = 'INSERT INTO %s (%s, %s, %s, %s, %s, %s, %s) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';

$GLOBALS['DBQUERY_BOSS'] = 'INSERT INTO %s (%s, %s, %s) VALUES (\'%s\', \'%s\')';

$GLOBALS['DBQUERY_SUPAPUPA'] = 'INSERT INTO items (object_id, owner_id, item_id, count, enchant_level, loc, loc_data) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';
$GLOBALS['DBQUERY_SHOP_ENCH'] = 'INSERT INTO items (object_id, owner_id, item_id, count, enchant_level, loc, loc_data) VALUES (\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\')';

