<?php

/* ****************************************************************** /
	 -----------------------------------------------------------
	 -                                                         -
	- ######################################################### -
	- Dragon Eye CMS System							            -
	- Visit www.DragonEyeCMS.com system in order to report BUGS -
	- For contact, send an email at michael9ufo@yahoo.co.uk		-
	- Note* This is an open-source project (free for anyone)    -
	- In order to use it you must only keep our copyright       -
	- ######################################################### -
	-                                                           -
	- Best regards,                                             -
	 -		Michael9ufo                                        -
	 -----------------------------------------------------------
/* ***************************************************************** */

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_TABLE'] = 'accounts';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_NAME'] = 'login';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_PASS'] = 'password';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_MAIL'] = 'email';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_ACC_LVL'] = 'access_level';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_LAST_LOGGED'] = 'lastactive';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_REFER_POINTS'] = 'refer_points';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_VOTE_POINTS'] = 'vote_points';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_DONATE_POINTS'] = 'donate_points';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_FORUM_POINTS'] = 'forum_points';
$GLOBALS['DBSTRUCT_L2J_ACCOUNTS_SIGNATURE'] = 'signature';
$GLOBALS['DBSTRUCT_L2J_CHARS_TABLE'] = 'characters';
$GLOBALS['DBSTRUCT_L2J_CHARS_ACC'] = 'account_name';
$GLOBALS['DBSTRUCT_L2J_CHARS_ID'] = 'obj_Id';
$GLOBALS['DBSTRUCT_L2J_CHARS_NAME'] = 'char_name';
$GLOBALS['DBSTRUCT_L2J_CHARS_LEVEL'] = 'level';
$GLOBALS['DBSTRUCT_L2J_CHARS_PVP'] = 'pvpkills';
$GLOBALS['DBSTRUCT_L2J_CHARS_PK'] = 'pkkills';
$GLOBALS['DBSTRUCT_L2J_CHARS_CLAN'] = 'clanid';
$GLOBALS['DBSTRUCT_L2J_CHARS_CLASS'] = 'classid';
$GLOBALS['DBSTRUCT_L2J_CHARS_TITLE'] = 'title';
$GLOBALS['DBSTRUCT_L2J_CHARS_RECS'] = 'rec_have';
$GLOBALS['DBSTRUCT_L2J_CHARS_ONLINE'] = 'online';
$GLOBALS['DBSTRUCT_L2J_CHARS_ONLINE_TIME'] = 'onlinetime';
$GLOBALS['DBSTRUCT_L2J_CHARS_LAST_ACCESS'] = 'lastAccess';
$GLOBALS['DBSTRUCT_L2J_CHARS_NOBLE'] = 'nobless';
$GLOBALS['DBSTRUCT_L2J_CHARS_HERO'] = 'hero';

$GLOBALS['DBSTRUCT_L2J_CHARS_ACH1'] = 'a1';


$GLOBALS['DBSTRUCT_L2J_CHARS_VIEWSET'] = 'viewset';

$GLOBALS['DBSTRUCT_L2J_CLAN_TABLE'] = 'clan_data';
$GLOBALS['DBSTRUCT_L2J_CLAN_ID'] = 'clan_id';
$GLOBALS['DBSTRUCT_L2J_CLAN_NAME'] = 'clan_name';
$GLOBALS['DBSTRUCT_L2J_CLAN_LEVEL'] = 'clan_level';
$GLOBALS['DBSTRUCT_L2J_CLAN_CASTLE'] = 'hasCastle';
$GLOBALS['DBSTRUCT_L2J_CLAN_ALLY'] = 'ally_id';
$GLOBALS['DBSTRUCT_L2J_CLAN_LEADER'] = 'leader_id';
$GLOBALS['DBSTRUCT_L2J_CASTLE_TABLE'] = 'castle';
$GLOBALS['DBSTRUCT_L2J_CASTLE_ID'] = 'id';
$GLOBALS['DBSTRUCT_L2J_CASTLE_NAME'] = 'name';
$GLOBALS['DBSTRUCT_L2J_CASTLE_DATE'] = 'siegeDate';
$GLOBALS['DBSTRUCT_L2J_NPCS_TABLE'] = '';
$GLOBALS['DBSTRUCT_L2J_NPCS_ID'] = '';
$GLOBALS['DBSTRUCT_L2J_NPCS_NAME'] = '';
$GLOBALS['DBSTRUCT_L2J_NPCS_LEVEL'] = '';
$GLOBALS['DBSTRUCT_L2J_RAIDS_TABLE'] = '';
$GLOBALS['DBSTRUCT_L2J_RAIDS_ID'] = '';
$GLOBALS['DBSTRUCT_L2J_RAIDS_TIME'] = '';
$GLOBALS['DBSTRUCT_L2J_SKILLS_TABLE'] = 'character_skills';
$GLOBALS['DBSTRUCT_L2J_SKILLS_CID'] = 'char_obj_id';
$GLOBALS['DBSTRUCT_L2J_SKILLS_ID'] = 'skill_id';
$GLOBALS['DBSTRUCT_L2J_SKILLS_LEVEL'] = 'skill_level';
$GLOBALS['DBSTRUCT_L2J_SKILLS_CLASS'] = 'class_index';



$GLOBALS['DBSTRUCT_L2J_ITEMS_TABLE'] = 'items';

$GLOBALS['DBSTRUCT_L2J_ITEMS_OBJCECT'] = 'object_id';

$GLOBALS['DBSTRUCT_L2J_ITEMS_CID'] = 'owner_id';
$GLOBALS['DBSTRUCT_L2J_ITEMS_ID'] = 'item_id';
$GLOBALS['DBSTRUCT_L2J_ITEMS_COUNT'] = 'count';
$GLOBALS['DBSTRUCT_L2J_ITEMS_ENCHANT'] = 'enchant_level';
$GLOBALS['DBSTRUCT_L2J_ITEMS_LOC'] = 'loc';
$GLOBALS['DBSTRUCT_L2J_ITEMS_TYPE'] = 'loc_data';

$GLOBALS['DBSTRUCT_L2J_EPIC'] = 'epic_boss_spawn';
$GLOBALS['DBSTRUCT_L2J_EPIC2'] = 'bossId';
$GLOBALS['DBSTRUCT_L2J_EPIC3'] = 'respawn_Date';
$GLOBALS['DBSTRUCT_L2J_EPIC4'] = 'state';