<?php
//floods
$GLOBALS['CONFIG_FLOOD_LOGS_EXTRA'] = 'b8e7bb0ffe7dff1';
$GLOBALS['CONFIG_MAIN_FLOOD_BYPASS'] = '0.05';
$GLOBALS['CONFIG_MAIN_FLOOD_TIME'] = '900';
$GLOBALS['CONFIG_RECOVER_FLOOD_BYPASS'] = '30';
$GLOBALS['CONFIG_RECOVER_FLOOD_TIME'] = '60';
$GLOBALS['CONFIG_REGISTER_FLOOD_BYPASS'] = '900';
$GLOBALS['CONFIG_REGISTER_FLOOD_TIME'] = '900';
$GLOBALS['CONFIG_CPASS_FLOOD_BYPASS'] = '30';
$GLOBALS['CONFIG_CPASS_FLOOD_TIME'] = '60';
