<?php

// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_SHOP_ENABLED'] = '1';

$GLOBALS['CONFIG_SHOP_TELNET_IP'] = '127.0.0.1';
$GLOBALS['CONFIG_SHOP_TELNET_PORT'] = '12345';
$GLOBALS['CONFIG_SHOP_TELNET_PASSWORD'] = '123';
$GLOBALS['CONFIG_SHOP_TELNET_TIMEOUT'] = '15';

$GLOBALS['CONFIG_SHOP_CACHED_IP'] = '46.147.153.76';
$GLOBALS['CONFIG_SHOP_CACHED_PORT'] = '3306';
$GLOBALS['CONFIG_SHOP_CACHED_ADMIN'] = 'FGT';
$GLOBALS['CONFIG_SHOP_CACHED_TIMEOUT'] = '10';

$GLOBALS['CONFIG_SHOP_REFER_ENABLED'] = '1';
$GLOBALS['CONFIG_SHOP_VOTE_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_DONATE_ENABLED'] = '1';
$GLOBALS['CONFIG_SHOP_FORUM_ENABLED'] = '0';
$GLOBALS['CONFIG_SHOP_REFER'] = array(array('asd', array('444'), '44', '4', '4'));
$GLOBALS['CONFIG_SHOP_VOTE'] = array();
$GLOBALS['CONFIG_SHOP_DONATE'] = array(array('Drac', array('7575'), '2', '55', '0'), array('123', array('275'), '5', '11', '0'), array('Scroll of Escape', array('736'), '22', '1', '0'), array('Appella', array('7870'), '1', '1', '22'), array(':222:', array('222'), '22', '2', '22'), array('$Drac$', array('13'), '22', '22', '22'), array('D83DDE03', array('2'), '2', '2', '2'), array('$#DRAC#$', array('12'), '2', '2', '2'), array('$#D83DDE0A#$', array('2'), '2', '2', '2'));
$GLOBALS['CONFIG_SHOP_FORUM'] = array();