<?php


// Do not edit this file if you do not know what you do
// Better edit by accessing admin panel

$GLOBALS['CONFIG_TEMPLATE_DEFAULT'] = 'default';
$GLOBALS['CONFIG_TEMPLATE_SELECTED'] = 'default';
$GLOBALS['CONFIG_TEMPLATE_NAME'] = 'Default Template';
$GLOBALS['CONFIG_TEMPLATE_DESCRIPTION'] = 'Международный Lineage 2 Interlude x1. Официальная платформа JAVA.';
$GLOBALS['CONFIG_TEMPLATE_KEYWORDS'] = 'Lineage 2, la2, l2, craft, server, interlude, сервер, линейка, интерлюд, крафт, х10, х1, х2, х3, х5, база знаний';
$GLOBALS['CONFIG_TEMPLATE_AUTHOR'] = 'Ultra';
$GLOBALS['CONFIG_TEMPLATE_IMAGES'] = 'images';
$GLOBALS['CONFIG_TEMPLATE_DEFAULT_LANG'] = 'Ru';